

server: 
  port: 8081
  
spring : 
  datasource :
    url : jdbc:mysql://localhost:3306/orderservice
    username : root
    password : Nikhilr@911000100
    driver-class-name : com.mysql.cj.jdbc.Driver
    
  jpa :
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate :
      ddl-auto : update
      
  application: 
    name: ORDERSERVICE
#Take the configuration from Config server
  config: 
    import: configserver:http://localhost:9296
  
#  zipkin : 
#    base-url :  http://localhost:9411
#    
#  sleuth : 
#    sampler : 
#      probability : 1.0 
management : 
  sampler : 
    probability : 1.0
#    
#  zipkin : 
#    tracing :
#      endpoint : http://localhost:9411

  
    
#eureka: 
#  instance: 
#    prefer-ip-address: true
#  client: 
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED