spring: 
  application: 
    name: CONFIGSERVER
  cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/Nikhil-Ranadive-217/Spring-app-config-server
          clone-on-start: true
server:
  port: 9296
