server: 
  port: 8080
spring : 
  datasource :
    url : jdbc:mysql://localhost:3306/productservice
    username : root
    password : Nikhilr@911000100
    driver-class-name : com.mysql.cj.jdbc.Driver
    
  jpa :
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate :
      ddl-auto : update
      
  application: 
    name: PRODUCTSERVICE
#Take the configuration from Config server
  config: 
    import: configserver:http://localhost:9296

#  zipkin : 
#    base-url :  http://localhost:9411
#    
#  sleuth : 
#    sampler : 
#      probability : 1.0  
management : 
  sampler : 
    probability : 1.0
#    
#  zipkin : 
#    tracing : 
#      endpoint : http://localhost:9411
   
# we are using central repo i.e git there we have added this configuration and we will pick from there 
#we are removing the duplication of code since in every client we will have this code connecting to eureka server    
#eureka: 
#  instance: 
#    prefer-ip-address: true
#  client: 
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka
 