server: 
  port: 8082
  
spring : 
  datasource :
    url : jdbc:mysql://localhost:3306/paymentservice
    username : root
    password : Nikhilr@911000100
    driver-class-name : com.mysql.cj.jdbc.Driver
    
  jpa :
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate :
      ddl-auto : update
      
  application: 
    name: PAYMENTSERVICE
#Take the configuration from Config server
  config: 
    import: configserver:http://localhost:9296
